### ISSUE TITLE
Type Error t is not defined...

### ISSUE THREAD

**Issue by parasharrajat** [kswedberg/jquery-smooth-scroll#102]
i tried to add smooth scroll to my webpage, but sometimes it throw an error type Error t is not defined in console..

**Comment by kswedberg** [comment]
Thx for the report and sorry about the problem. I'm on vacation now so might not be able to look at it for a couple days. 

Are you using latest version from this repo? Minified version or unminified?

**Comment by parasharrajat** [comment]
I m using the minified latest version from jquery plugin website.

**Comment by kswedberg** [comment]
The jQuery plugin website has a very old version in it. As noted on the site, "The jQuery Plugin Registry is in read-only mode. New plugin releases will not be processed." 

Please use the one in this repo (https://github.com/kswedberg/jquery-smooth-scroll/blob/master/jquery.smooth-scroll.js) or on npm (running `npm install jquery-smooth-scroll`)
