### ISSUE TITLE
console.log in runtime

### ISSUE THREAD

**Issue by Daijobou** [kswedberg/jquery-smooth-scroll#103]
Only a hint. In line https://github.com/kswedberg/jquery-smooth-scroll/blob/master/jquery.smooth-scroll.js#L253 is a unnecessary console.log() outout. ;)

**Comment by kswedberg** [comment]
oops! thanks for letting me know, @Daijobou !

**Comment by kswedberg** [comment]
Fixed by 9090002f326aa36f0ecb066a9181fbf178ebfdcf
