### ISSUE TITLE
s.stop() is not a function

### ISSUE THREAD

**Issue by jennifer-mann** [kswedberg/jquery-smooth-scroll#104]
jQuery - v3.2.1
jQuery Smooth Scroll - v2.2.0

My code
```js
$("a").smoothScroll()
```

Everything I've written hits this error:
```
s.stop is not a function
```

**Comment by kswedberg** [comment]
Yikes! Thanks for the report. Will look into this asap. I'm guessing you've minified the script?

**Comment by kswedberg** [comment]
Hmm. Just tested locally with jQuery 3.2.1 and had no problems. Are you using a custom build of jQuery that doesn't include the animation/effects component? Are you using jQuery.noConflict() somewhere? What happens if you open developer tools and do something like `$('body').stop()` in the console?

**Comment by jennifer-mann** [comment]
Yes, I did figure this out. I was only including the slim version of jQuery, which did not include animations. Apologies!

**Comment by kswedberg** [comment]
Ah, good to know! thanks for the follow-up, @jennifer-mann
