### ISSUE TITLE
Request for scrolling upwards

### ISSUE THREAD

**Issue by ChrisTrenkamp** [kswedberg/jquery-smooth-scroll#105]
As a user, I want to be able to scroll upwards so that my table of contents can keep the selected item in view when randomly navigating.

Currently, when I try to use smoothScroll, the screen only scrolls downward, even if scrollTarget is set to an element that's above the view.

**Comment by kswedberg** [comment]
Hi @ChrisTrenkamp , I can't reproduce this problem in my tests or demos. Do you have a test case you can point me to? Or can you provide me with some code that you're using so I can try to replicate it?

**Comment by ChrisTrenkamp** [comment]
I ended up rolling out my own scrolling solution and deleted my test case, so I'll close this issue.
