### ISSUE TITLE
Scrolling not smooth

### ISSUE THREAD

**Issue by douwepausma** [kswedberg/jquery-smooth-scroll#106]
When I click the link it jumps instantly to the assigned div there's no scrolling animation. (I think I might be doing something wrong.)

**Comment by kswedberg** [comment]
Sounds like either the selector you're using for the link is incorrect or the the link is not in the DOM at the time you're calling `$(selector).smoothScroll()`. I would need more information (link to a demonstration of the problem or some code at least) before I could help troubleshoot any further.
