### ISSUE TITLE
Error if id contains Chinese

### ISSUE THREAD

**Issue by YuunYang** [kswedberg/jquery-smooth-scroll#110]
when a's id contains Chinese or Japanese(maybe), will got a uncaught error

![image](https://user-images.githubusercontent.com/15278220/43896634-1652b81a-9c0c-11e8-8821-4e7c58c2e866.png)

**Comment by kswedberg** [comment]
Hi @YuunYang , 

jQuery (and native DOM methods) will throw an error when selecting elements if the selector is not a [valid CSS identifier](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier). You can get around this by escaping the selector, using `CSS.escape()` and an optional polyfill. See [CSS Escapes](https://mathiasbynens.be/notes/css-escapes#javascript) for more information. For jQuery 3.0+, you can use [$.escapeSelector](https://api.jquery.com/jQuery.escapeSelector/). 

If you're using the `$.fn.smoothScroll()` method (for example, `$('a').smoothScroll();`), you'll need to use the `$.smoothScroll()` method instead. Something like this, maybe:

```js
$('a[href^="#"]').on('click', function(event) {
  event.preventDefault();
  $.smoothScroll({
    scrollTarget: CSS.escape(this.hash)
  });
});
```

Hope that helps!

**Comment by YuunYang** [comment]
@kswedberg Thanks, I will try

**Comment by YuunYang** [comment]
@kswedberg I solved my problem, by using **decodeURI**,  cause of error is indeed the specific symbol `%` but css.escape is not useful, it just skip the error, but it changes the url string, so the function become invalid

**Comment by kswedberg** [comment]
ok, glad you figured it out!
