### ISSUE TITLE
horizontal scroll

### ISSUE THREAD

**Issue by omidMolaverdi** [kswedberg/jquery-smooth-scroll#115]
Hi,

Thanks for the great package. 

Please can you advice how the horizontal scroll works?

**Comment by kswedberg** [comment]
You set the `direction` property to `'left'`. The demo page has an example:

```js
$('button.scrollhorz').bind('click', function(event) {
  $.smoothScroll({
    direction: 'left',
    scrollElement: $('div.scrollme'),
    scrollTarget: '.horiz'
  });
});
```

If you're scrolling the document, just remove the `scrollElement: $('div.scrollme'),` line.
