### ISSUE TITLE
How to redirect a new href without opening new tab ?

### ISSUE THREAD

**Issue by dat15021999** [kswedberg/jquery-smooth-scroll#116]

**Comment by dat15021999** [comment]
$('#id').click(function () {
                  window.open("https://github.com/kswedberg/jquery-smooth-scroll/issues/116");
});

This one automatically open a new tab.

**Comment by kswedberg** [comment]
Hi @dat15021999 , not sure why you're asking here, but I think you could do something like this:

```js
$('#id').click(function () {
  window.location.href = "#116";
});
```

You could also use `window.location.hash` instead of `window.location.href`.

That isn't going to get it to scroll smoothly, though. Not sure if that's what you want or not.

**Comment by dat15021999** [comment]
yeah, thank you.
I found it instead of using library.
