### ISSUE TITLE
Load different page and then smooth scroll within different page

### ISSUE THREAD

**Issue by karland** [kswedberg/jquery-smooth-scroll#61]
Hi, thanks for jquery-smooth-scroll. I think it is excellent. 

I would like the smooth scrolling to take place on a different page. So my element on `different-page.html` looks like

```
<a href="/index.html#to-chapter1"> To Chapter 1</a>
```

I thought I can use the `beforeScroll`-function. 

```
// smooth-scroll
$('a[href*=#]:not([href=#])').click(function() {
    $.smoothScroll({
        beforeScroll: function () {location.replace("/index.html");},
        offset: -120,
        scrollTarget: this.hash
    });
    return false;
});
```

However, `smooth-scroll` does not wait for the `beforeScroll`-function to be completed, i.e. the page to be loaded. Is there a way to make this happen? Thanks

**Comment by dpanfili** [comment]
@karland - thanks for the snippet. Helped me solve an issue.

**Comment by Naren-hybreeder** [comment]
Is the above code is working in 2020? I just copy and paste the karland answer but I am getting error in console.

![79851868-862afb00-83e3-11ea-82e2-5415e8ee06f6](https://user-images.githubusercontent.com/16729825/79852027-bf636b00-83e3-11ea-9687-d37c8e62d3b4.png)

**Comment by kswedberg** [comment]
@Naren-hybreeder , try putting quotes around the hash:

```js
$('a[href*="/"][href*="#"]')
//…
```

**Comment by Naren-hybreeder** [comment]
@kswedberg  Thanks for the reply, I tried, My above issue got resolved but when I click on anchor tag then I am getting error in the console. 

> 
 $.smoothScroll is not a function

![Screenshot 2020-04-21 at 10 46 20 PM](https://user-images.githubusercontent.com/16729825/79893602-ee98cd00-8421-11ea-8d73-d0afab19e5dd.png)


I tried the below code which is working for me. I tried below code from one page to anoter page and it's working perfeclty but this code is not working on the same page.
 ```
$(document).ready(function() {
        $('html, body').hide();
        if (window.location.hash) {
            setTimeout(function() {
                $('html, body').scrollTop(0).show();
                $('html, body').animate({
                    scrollTop: $(window.location.hash).offset().top-100
                    }, 1000)
            }, 0);
        }
        else {
            $('html, body').show();
        }
    });
```

**Comment by dpanfili** [comment]
@Naren-hybreeder - maybe try [noConflict](https://api.jquery.com/jQuery.noConflict/) solution? I usually experience this issue if I'm trying to minimize, defer, or Async JS files.

**Comment by kswedberg** [comment]
@Naren-hybreeder , it's hard to troubleshoot without seeing what you're doing, but @dpanfili could be right. You might have more than one instance of jQuery loading on the page. Or, you're calling `$.smoothScroll` before the smooth scroll plugin has been loaded and parsed.
