### ISSUE TITLE
Scroll after page load

### ISSUE THREAD

**Issue by sitte** [kswedberg/jquery-smooth-scroll#68]
Hello. Is it possible to run scroll to "PointOnPage" element just after page load?
For example somebody navigates to 
http://PageURL.com/supage.html#PointOnPage
from external page?

Best regards
Barto

**Comment by kswedberg** [comment]
@LL782 : thanks for answering @sitte 's question!

**Comment by LL782** [comment]
@kswedberg my pleasure
