### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by BenRacicot** [kswedberg/jquery-smooth-scroll#71]
Hello, I've loaded up Smooth-Scroll for the first time and am getting a strange error: 
Uncaught TypeError: Cannot read property 'top' of undefined
I've gone through the code and all dependencies are loading correctly. 
Thanks!

UPDATE: I had the link Id's setup like a traditional 'on-page' anchor link would go. I've read through the examples to see how Smooth-Scroll works. Thanks for building it.

**Comment by kswedberg** [comment]
Ah, glad you got it working!
