### ISSUE TITLE
Disable mouse wheel while page is scrolling

### ISSUE THREAD

**Issue by skynet** [kswedberg/jquery-smooth-scroll#73]
With smoothScroll event, for example on a "go to top" click, if mouse wheel rotates a flickering happens. Is it possible to disable mouse wheel during smooth-scrolling?

**Comment by kswedberg** [comment]
Have you tried to do this by using the `beforeScroll` and `afterScroll` callback options? I haven't worked with mouse wheel behavior before, but maybe you could bind a listener in the beforeScroll callback to prevent the default mousewheel event from firing and then unbind the listener in the afterScroll callback.
