### ISSUE TITLE
Duplicate npm packages?

### ISSUE THREAD

**Issue by MiniGod** [kswedberg/jquery-smooth-scroll#77]
Why is this module published to multiple npm packages with different names?

https://www.npmjs.com/package/smooth-scroll
https://www.npmjs.com/package/jquery.smooth-scroll
https://www.npmjs.com/package/jquery-smooth-scroll

The latter one is the most downloaded one (10x more than the others combined), and most up to date.

How about unpublishing the others?

**Comment by kswedberg** [comment]
Thanks a lot for the report! And sorry about the confusion. This note from https://docs.npmjs.com/cli/unpublish gives me pause:

> **It is generally considered bad behavior to remove versions of a library that others are depending on!**

> Consider using the `deprecate` command instead, if your intent is to encourage users to upgrade.

What do you think? Should I just deprecate them?

**Comment by MiniGod** [comment]
Deprecation definitely sounds best, if that also hides it from search results.

**Comment by kswedberg** [comment]
I deprecated https://www.npmjs.com/package/jquery.smooth-scroll and updated its readme. I also removed https://www.npmjs.com/package/smooth-scroll entirely. I hope that helps avoid the confusion.
