### ISSUE TITLE
Not working in div with SVG?

### ISSUE THREAD

**Issue by Daijobou** [kswedberg/jquery-smooth-scroll#80]
I have a div with a big svg with d3 elements (nodes).
~~~~~
<div id="test" style="overflow:auto"><svg>.....<g id="myID">.....</svg></div>
~~~~~

this setting scroll, but not to correct position (horizontal).
~~~~~
$.smoothScroll(
{
    scrollElement: $('#test'),
	scrollTarget: '#myID'
});
~~~~~
The vertical position is correct, but the horizontal positionis is 0.

Is this with smoothScroll not possible or my mistake?

**Comment by kswedberg** [comment]
@Daijobou It's hard to know without looking at what's going on, but each call to smoothScroll only works in one direction, either `direction: 'top'` or `direction: 'left'` (it's `direction: 'top'` by default). So you could try calling it twice, the second time doing `$.smoothScroll({ scrollElement: $('#test'), scrollTarget: '#myID', direction: 'left' }); ` and see if that works. Please let me know if that solves it for you.

**Comment by Daijobou** [comment]
Thank you. I have solved it with jquery direclty and "center" it in viewport (vertical+horizontal). I think what you said is the solution, I close this false report. Sorry :)

**Comment by kswedberg** [comment]
Glad you got it to work!
