### ISSUE TITLE
smoothscroll missing the destination,gets closer at multiple clicks 

### ISSUE THREAD

**Issue by sgtpwnd** [kswedberg/jquery-smooth-scroll#81]
Hello and thank you for the plugin, First off I had this working perfectly before and im not sure why all the sudden im getting a different result, here is my html
alternatively you can look at it at,
metrodetroitmusic.com
 The last thing I added before this happened was add a jsonp call instead of a json call

<html>
<head>
  <title> Detroit Music App </title>
<link rel="stylesheet" media="screen" href="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link href='https://fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Offside' rel='stylesheet' type='text/css'>
<meta charset="UTF-8" />          
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="Awesome videos!" />
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/main.css">
<link rel="icon" type="images/png" href="images/wave.jpg">
</head>
<body ng-app="detroitMusicApp" id="container">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
          </button>
         
        </div>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="nav"><a href="#landing" id="metro">Metro Music</a></li>
            <li class="nav"><a href="#results">Listen</a></li>
                <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Upload <span class="caret"></span></a>
                  <ul class="dropdown-menu">                 
                        <li><a class="eventLink" href="https://tourbox.songkick.com/events/new" target="_blank">Event</a></li>
                        <li role="separator" class="divider"></li>
                    <li>
                          <h4>Video</h4>
                          <span id="signinButton" class="pre-sign-in">
                              <span
                                  class="g-signin"
                                  data-callback="oauth2Callback"
                                  data-clientid="463546373689-fkki0qlb23hegub236t2a2l9mgol5cdm.apps.googleusercontent.com"
                                  data-cookiepolicy="single_host_origin"
                                  data-scope="https://www.googleapis.com/auth/youtube.readonly https://www.googleapis.com/auth/youtube.upload">
                              </span>
                            </span>
                            
                            <div id="upload">
                                <div class="post-sign-in">
                                  <div>
                                    <img id="channel-thumbnail">
                                    <span id="channel-name"></span>
                                  </div>

                            <form id="upload-form">
                              <div>
                                <label for="title">Title:</label>
                                <input id="title" type="text" value="Default Title">
                              </div>
                              <div>
                                <label for="description">Description:</label>
                                <textarea id="description">Default description.</textarea>
                              </div>
                              <div>
                                <input id="file" type="file">
                              </div>
                                <input id="submit" type="submit" value="Upload">
                                <input type="reset" value="Reset Form">
                            </form>

                            <div class="during-upload">
                              <p><span id="percent-transferred"></span>% done (<span id="bytes-transferred"></span>/<span id="total-bytes"></span> bytes)</p>
                              <progress id="upload-progress" max="1" value="0"></progress>
                            </div>

                            <div class="post-upload">
                              <p>Uploaded video with id <span id="video-id"></span>. Polling for status...</p>
                              <ul id="post-upload-status"></ul>
                              <div id="player"></div>
                            </div>
                          </div>
                        </div>
                    </li>
                  </ul>

            <li class="nav"><a href="#attend">Attend</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li class="nav playlist"><div><select id="options"></select></div></li>
            <li class="nav playlist"><input id="value" type="text" placeholder="Enter playlist name"required></li>
            <li class="nav playlist"><button id="playlistSubmit" name="data" type="button" onclick="addToPlaylistIfExists()">Submit</button></li>
            <li class="nav"><div class="embed"><button class="pause"><i class="fa fa-pause"></i></button></div></li>
            <li class="nav"><div class="embed"><button class="play"><i class="fa fa-play"></i></button></div></li>
            <li class="nav"><div class="embed"><button class="stop"><i class="fa fa-stop"></i></button></div></li>
          </ul>
        </li>
      </ul>

        </div>
      </div>
    </nav>

  

    <div class="container-fluid">
      <div class="metro">
      <h3> Metro Music Detroit </h3> </div>
      <h5 id="tag">listen.upload.attend.</h5>
    <div id="wrapper">       
    </div>
    <div class="border">
    <img id="landingFooter" src="images/landingFader.png">
    </div>
    </div>

     
         <div class="container-fluid">
    <h2 class="catHeader" id="catHeader">Playlists</h2></div>
    <div id="categories">
        <div class="rap">
          <button onclick="runCategoryApi(rapMusicId)"><li class="nav"><a href="#music"><img src="images/rap2.jpg"></a>
          <h3> rap/hip-hop</h3></button>
        </div>
        <div class="rock">
          <button onclick="runCategoryApi(rockMusicId)"><li class="nav"><a href="#music"><img src="images/rock2.jpg"></a>
          <h3>rock</h3></button>
        </div>
        <div class="alt">
          <button onclick="runCategoryApi(punkMusicId)"><li class="nav"><a href="#music"><img src="images/alternative2.jpg"></a>
          <h3>alternative</h3></button>
        </div>
        <div class="country">
          <button onclick="runCategoryApi(countryMusicId)"><li class="nav"><a href="#music"><img src="images/country2.jpg"></a>
          <h3>country</h3></button>
        </div>
        <div class="jazz">
          <button onclick="runCategoryApi(jazzMusicId)"><li class="nav"><a href="#music"><img src="images/jazz2.jpg"></a>
          <h3>jazz</h3></button>
        </div>
        <div class="blues">
          <button onclick="runCategoryApi(bluesMusicId)"><li class="nav"><a href="#music"><img src="images/blues2.jpg"></a>
          <h3>blues</h3></button>
        </div>
        <div class="classical">
          <button onclick="runCategoryApi(classicalMusicId)"><li class="nav"><a href="#music"><img src="images/classical2.jpg"></a>
          <h3>classical</h3></button>
        </div>
        <div class="gospel">
          <button onclick="runCategoryApi(gospelMusicId)"><li class="nav"><a href="#music"><img src="images/gospel2.jpg"></a>
          <h3>gospel</h3></button>
        </div>
        <div class="elect">
          <button onclick="runCategoryApi(elecDanMusicId)"><li class="nav"><a href="#music"><img src="images/electronic2.jpg"></a>
          <h3>electronic</h3></button>
        </div>
        <div class="urban">
          <button onclick="runCategoryApi(urbanMusicId)"><li class="nav"><a href="#music"><img src="images/urban2.jpg"></a>
          <h3>urban</h3></button>
        </div>
      </div>

      
    <div id="sectionYoutube" class="col-md-6 col-md-offset-3">
      <div>
       <div id="music"></div>
     </div>
         <div id="results">
        <div class="video">
        </div>
        </div> 
      </div>
     </div>
     <div class="col-md-6 col-md-offset-3">
   
                <h1 class="w100 text-center"><img id="youtube" src="images/youtube-logo.jpg">music search</h1>
    </div>
            <div class="row" data-scope="https://www.googleapis.com/auth/youtube.readonly">
                <div class="col-md-6 col-md-offset-3">
                    <form id="searchForm" action="#">
                        <p><input type="text" id="search" placeholder="Type something..." autocomplete="on" class="form-control" /></p>
                        <p><input  type="submit" value="Search" class="form-control btn btn-info w100"></p>
                    </form>
                    </div>
  
     
 

<div ng-controller="eventCtrl">
</div>
   
    <div class="container-fluid">
    <div class="col-md-12"><div id="attend"></div>
    <h2 class="eventsHead">Attend </h2>

      
    <script src="//instansive.com/widget/js/instansive.js"></script><iframe src="//instansive.com/widgets/510d0df4f25e0827bcabaaf7193b15da0c640cf5.html" id="instansive_510d0df4f2" name="instansive_510d0df4f2"  scrolling="no" allowtransparency="true" class="instansive-widget" style="width: 85%; border: 0; overflow: hidden;"></iframe>
    <p id="hashtag">#detroitmusic</p>

      

    <div id="events">
    </div>
    </div>
    </div>
    </div>
  </div>

    <footer>
      <p>&copy; metro music | 2015</p>
    </footer>
<script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>
<script type="text/javascript" charset="utf-8" src="js/jquery.tubular.1.0.js"></script>
<script type="text/javascript" src="js/smoothScroll/smoothScroll.js"></script>
<script type="text/javascript" src="js/ntzYoutubeEmbed.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/app.js"></script>
<script type="text/javascript" src="https://apis.google.com/js/client:plusone.js?onload=initializeGapi"></script>
</body>
</html>

**Comment by sgtpwnd** [comment]
the weird thing is every time you click it it gets closer, after like the 5th click its where it should be, Ive tried divs with no height so it could only be returning one area and not the middle of it but that didnt work

**Comment by sgtpwnd** [comment]
oh i fiqured it out, i put a zoom on the page in css, that was what is responsible

**Comment by kswedberg** [comment]
Glad you got it worked out!
