### ISSUE TITLE
Add to bower ?

### ISSUE THREAD

**Issue by getphuture** [kswedberg/jquery-smooth-scroll#82]
Would it be possible to add it to Bower please ?

**Comment by kswedberg** [comment]
Sorry. I haven't used bower in over a year and was under the impression that bower is effectively dead. (see https://github.com/rackt/redux/issues/944#issuecomment-154858804 for example). I also thought it was possible to set up your .bowerrc to point to package.json for your bower dependencies. Nevertheless, I don't want to make things difficult for people, so if it's a big pain not to have the bower.json file in here, let me know and I'll put it back in.

**Comment by kswedberg** [comment]
Also, this: https://github.com/bower/bower/pull/1748#issuecomment-150104311
So, while rumors of Bower's demise might be exaggerated, that comment thread doesn't exactly inspire confidence.

**Comment by getphuture** [comment]
Thank you very much for your help, I appreciated a lot.
Let's forgot about Bower, it looks like I should consider npm seriously.
Cheers

**Comment by kswedberg** [comment]
@getphuture : changed my mind. Put a bower.json file back in for Bower support, since people apparently are still using it (c768feee907f0148c0c929de8c95729b2caa9040) so you should be able to do `bower install jquery-smooth-scroll`
