### ISSUE TITLE
smooth-scroll is causing a conflit

### ISSUE THREAD

**Issue by Redani** [kswedberg/jquery-smooth-scroll#86]
Dear Karl, thanks for your lovely plugin ;)

I have started to use it but it's causing me a conflict with another scrollable function I use (jquerytools) :/ how can I fix this?

Thanks a lot and happy holidays ;)

**Comment by kswedberg** [comment]
happy holidays to you, too! It must be hard to know if smooth-scroll is causing the conflict or if jquerytools is causing it, right? I've never used jquerytools, so I can't really help without seeing an example of the problem. If you point me to a URL, I'll investigate.

**Comment by Redani** [comment]
Thanks Karl for your reply and also for your wishes :)

Haha, yes you're right about accusing which one is causing the conflict :)
here is the link where I had this conflict:
https://www.optigura.com/account/signin.php, i have unfortunately disabled
smooth-scroll until i solve the problem. If you click on "Mot de passe
oublié ?" the scrollable plugin of jquerytool get's in action!

Thanks a lot for your assistance

2015-12-18 19:11 GMT+00:00 Karl Swedberg <notifications@github.com>:

> happy holidays to you, too! It must be hard to know if smooth-scroll is
> causing the conflict or if jquerytools is causing it, right? I've never
> used jquerytools, so I can't really help without seeing an example of the
> problem. If you point me to a URL, I'll investigate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kswedberg/jquery-smooth-scroll/issues/86#issuecomment-165873528>
> .
>



-- 
Réda Hassani
+212 6 11 52 38 08
+33 6 0931 8938
http://www.moroccan-arts.com/

**Comment by kswedberg** [comment]
I'm afraid there isn't much I can do to help if I can't see the problem. Also, the scripts that I *can* see are all minified and obfuscated, making it nearly impossible to determine what's going on.

**Comment by Redani** [comment]
oh that's a bad news, and can't do much about the code :/

well, i've already found the problem, i use jquerytools plugin that has a
scrollable function:
http://jquerytools.github.io/demos/scrollable/index.html and in your plugin
you have this: t.fn.extend({scrollable:function(t){var
e=s.call(this,{dir:t});return this.pushStack(e)} ... which is causing a
conflict...
so i'm wondering if i can renale your "scrollable" by "smoothscrollable"
for example...

2015-12-20 20:19 GMT+00:00 Karl Swedberg <notifications@github.com>:

> I'm afraid there isn't much I can do to help if I can't see the problem.
> Also, the scripts that I *can* see are all minified and obfuscated,
> making it nearly impossible to determine what's going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kswedberg/jquery-smooth-scroll/issues/86#issuecomment-166151312>
> .
>



-- 
Réda Hassani
+212 6 11 52 38 08
+33 6 0931 8938
http://www.moroccan-arts.com/

**Comment by kswedberg** [comment]
Sure. Give it a shot.

**Comment by Redani** [comment]
well, it seems to be working, but i'm confused about your "scrollable"
function, what is it for ?

2015-12-20 21:49 GMT+00:00 Karl Swedberg <notifications@github.com>:

> Sure. Give it a shot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kswedberg/jquery-smooth-scroll/issues/86#issuecomment-166157232>
> .
>



-- 
Réda Hassani
+212 6 11 52 38 08
+33 6 0931 8938
http://www.moroccan-arts.com/

**Comment by kswedberg** [comment]
In my plugin `$.fn.scrollable` is a [traversing](https://api.jquery.com/category/traversing/) method that filters a jQuery collection to include only the elements that are scrollable. For example, if I were to do `$('html, body').scrollable()`, it would return a jQuery object consisting of …

* the `body` element in Chrome
* the `html` element in Firefox
* both `html` and `body` in older versions of Opera

**Comment by kswedberg** [comment]
Closing this for now. Let me know if you have any other questions.

**Comment by Redani** [comment]
OK, thank you very much for the explanations ;)
So, you confirm that naming "scrollable" into "smoothScrollable" will have
no consequences ?

Thanks

2015-12-21 14:53 GMT+00:00 Karl Swedberg <notifications@github.com>:

> In my plugin $.fn.scrollable is a traversing
> <https://api.jquery.com/category/traversing/> method that filters a
> jQuery collection to include only the elements that are scrollable. For
> example, if I were to do $('html, body').scrollable(), it would return a
> jQuery object consisting of …
>
>    - the body element in Chrome
>    - the html element in Firefox
>    - both html and body in older versions of Opera
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kswedberg/jquery-smooth-scroll/issues/86#issuecomment-166322946>
> .
>



-- 
Réda Hassani
+212 6 11 52 38 08
+33 6 0931 8938
http://www.moroccan-arts.com/

**Comment by Redani** [comment]
Hi again Karl,
I've just realised that I have more errors :/ i'll PM you a link tot a test page so you can also see the problem of scrollable...

Thanks a lot

**Comment by kswedberg** [comment]
Ok, thanks. 

--Karl
