### ISSUE TITLE
BBQ with offset

### ISSUE THREAD

**Issue by FelixINX** [kswedberg/jquery-smooth-scroll#87]
Hi,

I have a bootstrap website, with Smooth Scrool with Back Button Support. Currently, when clicking on a button, I cannot see the first 60px of my div (the space of the navbar. I have seen an offset option, but it dosen't seen to be working. I am not sure were to put this. This is the only code that I added for the plugin (except of the base script):
```javascript
$(document)
    .on('click', 'a[href*="#"]', function() {
      if ( this.hash && this.pathname === location.pathname ) {
        $.bbq.pushState( '#/' + this.hash.slice(1) );
        return false;
      }
    })
    .ready(function() {
      $(window).bind('hashchange', function(event) {
        var tgt = location.hash.replace(/^#\/?/,'');
        if ( document.getElementById(tgt) ) {
          $.smoothScroll({scrollTarget: '#' + tgt});
        }
      });
      $(window).trigger('hashchange');
    });
```

Where do I need to but the Offset settings?

Here is the demo : http://7freres.com/services-dete-new#/construction

Thank you!

**Comment by kswedberg** [comment]
You would put the `offset` option  alongside the `scrollTarget` option, like so:

```js
$.smoothScroll({
  scrollTarget: '#' + tgt,
  offfset: -62
});
```

**Comment by kswedberg** [comment]
Any luck with that? Shall we close this issue?

**Comment by FelixINX** [comment]
Sorry about the delay. I just finished school :smile: . Here is the updated code:
```javascript
/**
 * Smoot-scrool config
 */
 
 $(document)
    .on('click', 'a[href*="#"]', function() {
      if ( this.hash && this.pathname === location.pathname ) {
        $.bbq.pushState( '#/' + this.hash.slice(1) );
        return false;
      }
    })
    .ready(function() {
      $(window).bind('hashchange', function(event) {
        var tgt = location.hash.replace(/^#\/?/,'');
        if ( document.getElementById(tgt) ) {
          $.smoothScroll({scrollTarget: '#' + tgt, offfset: -62});
        }
      });
      $(window).trigger('hashchange');
    });
```
Dosen't work for now...

**Comment by kswedberg** [comment]
Congratulations on finishing school! 

I'm getting a 404 when going to the demo page.

**Comment by FelixINX** [comment]
Link updated http://7freres.com/services-dete-new#/construction

**Comment by kswedberg** [comment]
You have three "f"s in `offfset`. Change that to `offset`, and it should work.

**Comment by FelixINX** [comment]
It's perfect!

**Off-Topic** One last question, why `-62` and not `62`?

**Comment by kswedberg** [comment]
Glad it's working now! It's `-62` because you want to decrease the scrollTop of the window. As you go down the page, the scrollTop increases; as you go up, it approaches 0. So, the scrolling animation needs to adjust to account for the fixed nav, moving back up. Hope that makes sense.

**Comment by FelixINX** [comment]
Make sense. Thanks for this!
