### ISSUE TITLE
On firefox (both osx and windows), with scroll-behavior: smooth, does not work when on top of page.

### ISSUE THREAD

**Issue by mlynarczyk** [kswedberg/jquery-smooth-scroll#90]
With 

```
html, body {
  scroll-behavior: smooth;
}
```

jquery.smooth-scroll.js does not scroll on firefox (only firefox supports this css property) when scrollbar is in initial state, after you scroll a pixel or two it works again. Ended up getting rid of scroll-behavior: smooth;

**Comment by kswedberg** [comment]
Thanks for report. I'm working on a fix.

**Comment by kswedberg** [comment]
Fixed by 0987f08fd826f6b0e7e453add81d8f674f97f384
