### ISSUE TITLE
Should do nothing if no scrollable match is found

### ISSUE THREAD

**Issue by aviemet** [kswedberg/jquery-smooth-scroll#92]
If there is no match in DOM to scroll to, it scrolls to the top of the page. Should do nothing instead.

**Comment by kswedberg** [comment]
thanks for the report. I have a fix that I'll try to push tomorrow. I'm continuing on the assumption that if there is no match in the DOM, neither the `beforeScroll` nor the `afterScroll` callbacks should fire either. Sound right?
