### ISSUE TITLE
jQuery 3.X deprecation warning

### ISSUE THREAD

**Issue by chrisdl** [kswedberg/jquery-smooth-scroll#97]
Hey

Great library. jQuery migrate (https://code.jquery.com/jquery-migrate-3.0.0.js) raises a deprecation warning about the swing animation.

```
JQMIGRATE: easing function "jQuery.easing.swing" should use only first argument
```

It is only deprecated, not removed but it will probably stop working for next major version of jQuery.

**Comment by kswedberg** [comment]
Interesting! I'm seeing deprecation warnings for `delegate`, `undelegate` and `bind`, but not for `jQuery.easing.swing`. Can you point me to a page that is experiencing the issue?

**Comment by chrisdl** [comment]
Actually I can't! Not sure why I can't reproduce on jsfiddle I had no issues reproducing on my local environment. and the version of the lib should be the same.

The behavior in the fiddle mimics my local

```
on ready
    on click
        scroll to target
```

It was only on the smoothscroll actually being called that jquery migrate logged out to jsconsole that there was an issue. I'll try to think what the difference between the fiddle and my local could be, but as of right now im stumped for reproducing.

**Comment by kswedberg** [comment]
Strange! Thanks for looking into it. And if you do track down the source of the problem, please let me know.

**Comment by chrisdl** [comment]
Np. So want me to close down the issue for now, and you can simply file it away in your gray matter that something might be funky in the future with how you are calling jquery animations?

**Comment by kswedberg** [comment]
Sure, that would be great. Thanks again.
