### ISSUE TITLE
update to bower

### ISSUE THREAD

**Issue by lucidlemon** [kswedberg/jquery-smooth-scroll#99]
the bower versions are pretty old and not working currently:

`Available versions in https://github.com/kswedberg/jquery-smooth-scroll.git: 1.7.2, 1.7.1, 1.7.0, 1.6.2, 1.6.1, 1.6.0, 1.5.7, 1.5.6, 1.5.5, 1.5.4, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.13, 1.4.12, 1.4.11, 1.4.10, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2`

**Comment by kswedberg** [comment]
Thanks for bringing that to my attention. I pushed a new tag with a `bower.json` that has the current version in it, so I'm hoping that will fix things. Can you please try again and let me know if it's working now?

**Comment by lucidlemon** [comment]
`bower info jquery-smooth-scroll`

now prints:

```
Available versions:
  - 2.0.1
  - 1.7.2
  - 1.7.1
  - 1.7.0
  - 1.6.2
  - 1.6.1
  - 1.6.0
...
```

thanks!
